version: 2.1

orbs:
  node: circleci/node@5

jobs:
  build-and-test:
    docker:
      - image: cimg/node:20.9.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Lint
          command: |
            yarn lint
            yarn lint:ts
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - build
            - dist
            - public
            - .output
            - .next
            - .docusaurus

  deploy:
  docker:
    - image: cimg/base:stable
  steps:
    - attach_workspace:
        at: .
    - run:
        name: Build and push Docker image
        command: |
          docker build -t myapp:$CIRCLE_WORKFLOW_ID .
          docker push myapp:$CIRCLE_WORKFLOW_ID

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
