version: 2.1

orbs:
  node: circleci/node@5

jobs:
  build-and-test:
    docker:
      - image: cimg/node:20.9.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Lint
          command: |
            yarn lint
            yarn lint:ts
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - build
            - dist
            - public
            - .output
            - .next
            - .docusaurus

  deploy:
    docker:
      - image: cimg/node:20.9.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy
          command: |
            # 배포 명령어를 여기에 작성하세요.
            yarn start

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
